[package]
name = "break-hash-example"
version = "1.0.0"
edition = "2024"
license = "MIT"
description = "An example of changing Hash impl in a minor version bump"
repository = "https://github.com/kevinheavey/break-hash-example"
